import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

import ProvidersComponent from '@/components/ProvidersComponent'
import NavigationComponent from '@/components/NavigationComponent'
import FooterComponent from '@/components/FooterComponent'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvidersComponent>
          <NavigationComponent />
          <div className="min-h-[100vh] flex flex-col justify-between">
            {children}
            <FooterComponent />
          </div>
        </ProvidersComponent>
      </body>
    </html>
  )
}
